### ISSUE TITLE
At least two trackers should be listed in parameters.

### ISSUE THREAD

**Issue by PeterHuang2015** [jwlim/tracker_benchmark#1]
## Using single tracker for -t parameter caused index out of range error in python
Hi, @jwlim I tested the code and found the requirement as stated above .Should there be at least two trackers for comparation as designed or could it be fixed?

## And is there an effective way to view ground truth along with tracking result bounding box at the same time without coding in this benchmark?
That's another question, thx for sharing the code.

**Comment by jwlim** [comment]
Hi, both issues are resolved in the recent updates. Thanks for suggestion!
