### ISSUE TITLE
init_omit.txt?

### ISSUE THREAD

**Issue by chenfsjz** [jwlim/tracker_benchmark#24]
Hi, thank you for your source code! And I want to evaluate the algorithm on OTB-100, and there is a imitOmit.txt files included in the tracker_benchmark_v1.0, and where can I find the imitOmit files of the OTB100 dataset?

**Comment by changhee1** [comment]
Hi, @chenfsjz 
you can download the updated dataset via 'run_tracker.py' and 'init_omit.txt' files are included in each sequence.

**Comment by chenfsjz** [comment]
Thank your very much!

**Comment by laisimiao** [comment]
> Thank your very much!

I download one sequence(just for test) by ranning 'run_tracker.py', but under that sequence dir, there is no 'init_omit.txt'. Why? How do you solve this?
(Beacuse you say 'thank you', I think you have done with this)
I would appreciate it if you could reply to me!!

**Comment by laisimiao** [comment]
> Hi, @chenfsjz
> you can download the updated dataset via 'run_tracker.py' and 'init_omit.txt' files are included in each sequence.

It seems  'init_omit.txt' file included in each sequence by downloading the updated dataset is same as '....txt' in in the tracker_benchmark_v1.0 initOmit directory? Right?
Look foward to your reply!!
